######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 9 16:15:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AttachmentTreeModel.h \
           exAttachment.h \
           ExtraTreeModel.h \
           PlugInManager.h \
           SceneFile.h
SOURCES += exAttachment.cpp
