######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 12 21:30:14 2012
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AttachmentPlugIn.h exAttachment.h
SOURCES += exAttachment.cpp
